export const data = [
  {
    id: 1,
    image: "/images/sushi.jpeg",
    title: "Sushi",
    description: "Sushi enak",
    price: 123000,
  },
  {
    id: 2,
    image: "/images/sushi.jpeg",
    title: "Sushi",
    description: "Sushi mantap",
    price: 93000,
  },
  {
    id: 3,
    image: "/images/sushi.jpeg",
    title: "Sushi",
    description: "Sushi jago",
    price: 73000,
  },
  {
    id: 4,
    image: "/images/sushi.jpeg",
    title: "Sushi",
    description: "Sushi wenak",
    price: 53000,
  },
  {
    id: 5,
    image: "/images/sushi.jpeg",
    title: "Sushi",
    description: "Sushi wow",
    price: 83000,
  },
  {
    id: 6,
    image: "/images/sushi.jpeg",
    title: "Sushi",
    description: "Sushi enak",
    price: 123000,
  },
  {
    id: 7,
    image: "/images/sushi.jpeg",
    title: "Sushi",
    description: "Sushi mantap",
    price: 93000,
  },
  {
    id: 8,
    image: "/images/sushi.jpeg",
    title: "Sushi",
    description: "Sushi jago",
    price: 73000,
  },
  {
    id: 9,
    image: "/images/sushi.jpeg",
    title: "Sushi",
    description: "Sushi wenak",
    price: 53000,
  },
  {
    id: 10,
    image: "/images/sushi.jpeg",
    title: "Sushi",
    description: "Sushi wow",
    price: 83000,
  },
];
